export { default as HomePageLayout } from './Layout.Home';
export { default as AboutPageLayout } from './Layout.About';
export { default as WorkPageLayout } from './Layout.Work';
export { default as Services } from './Layout.Services';
export { default as ProjectDetailPageLayout } from './Layout.ProjectDetail';
export { default as WritingPageLayout } from './Layout.Writing';
export { default as ArticlePageLayout } from './Layout.Article';
export { default as WritingByCategoryPageLayout } from './Layout.WritingByCategory';
export { default as PrivacyPolicyLayout } from './Layout.PrivacyPolicy';